# Generated by Django 5.2.17 on 2026-09-05 06:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quotations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NegotiationMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_type', models.CharField(choices=[('customer', 'Customer'), ('rep', 'Sales Rep'), ('system', 'System')], max_length=10)),
                ('author_name', models.CharField(blank=True, max_length=200)),
                ('message', models.TextField()),
                ('counter_discount_percent', models.DecimalField(blank=True, decimal_places=2, help_text='Counter-discount percentage proposed by the customer', max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('line_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='negotiation_messages', to='quotations.quotationline')),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='negotiation_messages', to='quotations.quotation')),
            ],
            options={
                'db_table': 'portal_negotiation_message',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='PortalToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('expires_at', models.DateTimeField()),
                ('is_used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='portal_tokens', to=settings.AUTH_USER_MODEL)),
                ('quotation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='portal_tokens', to='quotations.quotation')),
            ],
            options={
                'db_table': 'portal_token',
                'ordering': ['-created_at'],
            },
        ),
    ]
