# Generated by Django 5.2.17 on 2026-09-05 08:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quotations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(blank=True, max_length=300)),
                ('shipping_cost_weight', models.DecimalField(decimal_places=2, default=1.0, max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'fulfillment_warehouse',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FulfillmentSplit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.PositiveIntegerField()),
                ('shipment_count', models.PositiveIntegerField(default=1)),
                ('estimated_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('suggested', 'Suggested'), ('accepted', 'Accepted'), ('overridden', 'Overridden'), ('shipped', 'Shipped'), ('delivered', 'Delivered')], default='suggested', max_length=15)),
                ('promised_ship_date', models.DateField(blank=True, null=True)),
                ('actual_ship_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quotations.product')),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fulfillment_splits', to='quotations.quotation')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fulfillment.warehouse')),
            ],
            options={
                'db_table': 'fulfillment_split',
                'ordering': ['quotation', 'warehouse'],
            },
        ),
        migrations.CreateModel(
            name='StockLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_stock', models.PositiveIntegerField(default=0)),
                ('reserved', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_levels', to='quotations.product')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_levels', to='fulfillment.warehouse')),
            ],
            options={
                'db_table': 'fulfillment_stock_level',
                'unique_together': {('warehouse', 'product')},
            },
        ),
    ]
