# Generated by Django 5.2.17 on 2026-09-05 08:53

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('fulfillment', '0001_initial'),
        ('quotations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='warehouse',
            options={'ordering': ['name']},
        ),
        migrations.RenameField(
            model_name='stocklevel',
            old_name='quantity',
            new_name='in_stock',
        ),
        migrations.RemoveField(
            model_name='stocklevel',
            name='reorder_point',
        ),
        migrations.AddField(
            model_name='stocklevel',
            name='reserved',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='FulfillmentSplit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.PositiveIntegerField()),
                ('shipment_count', models.PositiveIntegerField(default=1)),
                ('estimated_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('suggested', 'Suggested'), ('accepted', 'Accepted'), ('overridden', 'Overridden'), ('shipped', 'Shipped'), ('delivered', 'Delivered')], default='suggested', max_length=15)),
                ('promised_ship_date', models.DateField(blank=True, null=True)),
                ('actual_ship_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.product')),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fulfillment_splits', to='quotations.quotation')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fulfillment.warehouse')),
            ],
            options={
                'db_table': 'fulfillment_split',
                'ordering': ['quotation', 'warehouse'],
            },
        ),
    ]
