# Generated by Django 5.2.17 on 2026-09-05 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fulfillment', '0001_initial'),
        ('quotations', '0002_product_cost_price_quotationline_cost_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fulfillmentsplit',
            name='is_backorder',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='stocklevel',
            name='reorder_point',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddConstraint(
            model_name='stocklevel',
            constraint=models.CheckConstraint(condition=models.Q(('reserved__lte', models.F('in_stock'))), name='stock_reserved_not_overdrawn'),
        ),
    ]
