# Generated by Django 5.2.17 on 2026-09-05 08:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0001_initial'),
        ('quotations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='quotation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='quotations.quotation'),
        ),
        migrations.AddField(
            model_name='payment',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='billing.invoice'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_plans', to='quotations.product'),
        ),
        migrations.AddField(
            model_name='upsellrule',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upsell_from', to='quotations.product'),
        ),
        migrations.AddField(
            model_name='upsellrule',
            name='suggested_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upsell_to', to='quotations.product'),
        ),
    ]
