# Generated by Django 5.2.17 on 2026-09-05 07:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_plans', to='core.product'),
        ),
        migrations.AddField(
            model_name='upsellrule',
            name='source_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upsell_sources', to='core.product'),
        ),
        migrations.AddField(
            model_name='upsellrule',
            name='target_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upsell_targets', to='core.product'),
        ),
    ]
