# Generated by Django 5.2.17 on 2026-09-05 08:53

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_initial'),
        ('core', '0001_initial'),
        ('quotations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscriptionplan',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='interval',
        ),
        migrations.RemoveField(
            model_name='upsellrule',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='upsellrule',
            name='margin_threshold',
        ),
        migrations.RemoveField(
            model_name='upsellrule',
            name='promotion_tag',
        ),
        migrations.RemoveField(
            model_name='upsellrule',
            name='source_product',
        ),
        migrations.RemoveField(
            model_name='upsellrule',
            name='target_product',
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='cancellation_refund_pct',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=5),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='cycle',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly')], default='monthly', max_length=15),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='proration_rule',
            field=models.CharField(default='daily_proration', max_length=50),
        ),
        migrations.AddField(
            model_name='upsellrule',
            name='is_promoted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='upsellrule',
            name='min_margin_pct',
            field=models.DecimalField(decimal_places=2, default=20, max_digits=5),
        ),
        migrations.AddField(
            model_name='upsellrule',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='upsell_from', to='core.product'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='upsellrule',
            name='suggested_product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='upsell_to', to='core.product'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=20, unique=True)),
                ('type', models.CharField(choices=[('one_time', 'One-Time'), ('recurring', 'Recurring')], default='one_time', max_length=15)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('paid', 'Paid'), ('overdue', 'Overdue'), ('cancelled', 'Cancelled')], default='draft', max_length=15)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='quotations.quotation')),
            ],
            options={
                'db_table': 'billing_invoice',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('method', models.CharField(default='bank_transfer', max_length=50)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('paid_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='billing.invoice')),
            ],
            options={
                'db_table': 'billing_payment',
            },
        ),
    ]
