# Generated by Django 5.2.17 on 2026-09-05 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_creditnote_subscription_payment_recorded_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditnote',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='credits', to='billing.invoice'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='anchor_day',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='subscription',
            name='current_invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='billing.invoice'),
        ),
        migrations.CreateModel(
            name='SubscriptionCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='billing.invoice')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='charges', to='billing.subscription')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('subscription', 'invoice'), name='unique_subscription_invoice_charge')],
            },
        ),
    ]
