import { ReactNode, useState } from 'react';
import { NavLink, useNavigate, useLocation } from 'react-router-dom';
import { useAuth } from '../../context/AuthContext';
import { useQueryClient, useQuery } from '@tanstack/react-query';
import { quotationsApi } from '../../api/quotations';
import { LayoutDashboard, FileText, ShieldCheck, Truck, CreditCard, Receipt, HeartPulse, BarChart3, Settings, Search, LogOut, Menu, X, RefreshCw, Layers, Package } from 'lucide-react';
const items = [
 {to:'/dashboard',label:'Overview',icon:LayoutDashboard},
 {to:'/quotations',label:'Quotations',icon:FileText},
 {to:'/approvals',label:'Approval desk',icon:ShieldCheck,roles:['admin','sales_manager','finance']},
 {to:'/fulfillment',label:'Fulfillment',icon:Truck,roles:['admin','sales_manager','finance']},
 {to:'/inventory',label:'Inventory',icon:Package,roles:['admin','sales_manager','finance']},
 {to:'/subscriptions',label:'Subscriptions',icon:CreditCard},
 {to:'/invoices',label:'Invoices & payments',icon:Receipt},
 {to:'/deal-health',label:'Deal health',icon:HeartPulse},
 {to:'/reports',label:'Reports',icon:BarChart3},
 {to:'/config',label:'Catalog & rules',icon:Settings,roles:['admin','sales_manager']},
];
export function AppShell({children}:{children:ReactNode}){
 const {user,logout}=useAuth(); const qc=useQueryClient();const navigate=useNavigate();const location=useLocation();const [mobile,setMobile]=useState(false);const [search,setSearch]=useState('');
 const visible=items.filter(i=>!i.roles||i.roles.includes(user?.role||''));
 const title=visible.find(i=>location.pathname.startsWith(i.to))?.label||'Workspace';
 const {data:quotes=[]}=useQuery({queryKey:['quotations'],queryFn:()=>quotationsApi.list(),refetchInterval:30000});
 const pending=quotes.filter(q=>q.status==='pending_approval').length;
 const nav=<><NavLink to="/dashboard" className="flex items-center gap-3 px-5 h-20 border-b border-slate-100"><span className="w-8 h-8 rounded-lg bg-primary text-white flex items-center justify-center"><Layers size={19}/></span><span className="text-lg font-semibold tracking-tight">DealFlow<span className="text-slate-400 font-normal">360</span></span></NavLink><div className="mx-4 my-5 px-3 py-3 border border-slate-200 rounded-lg"><div className="text-xs font-semibold">Sales workspace</div><div className="text-xs text-slate-500 mt-1">India · INR</div></div><nav aria-label="Main navigation" className="px-3 flex-1 space-y-1 overflow-y-auto">{visible.map(i=><NavLink key={i.to} to={i.to} onClick={()=>setMobile(false)} className={({isActive})=>`flex gap-3 items-center px-3 py-2.5 rounded-lg text-sm transition-colors ${isActive?'bg-blue-50 text-blue-700 font-semibold':'text-slate-600 hover:bg-slate-50'}`}><i.icon size={17} strokeWidth={1.65}/><span>{i.label}</span>{i.to==='/approvals'&&pending>0&&<span className="ml-auto text-[11px] bg-white border border-blue-100 rounded px-1.5">{pending}</span>}</NavLink>)}</nav><div className="p-4 border-t border-slate-200 mt-5 flex items-center gap-3"><div className="w-8 h-8 rounded-full bg-slate-100 grid place-items-center font-semibold text-xs">{user?.first_name?.[0]||user?.username?.[0]}</div><div className="min-w-0 flex-1"><strong className="block text-xs truncate">{user?.first_name||user?.username} {user?.last_name}</strong><span className="text-[11px] text-slate-500 capitalize">{user?.role.replaceAll('_',' ')}</span></div><button title="Sign out" aria-label="Sign out" className="icon-button" onClick={()=>{logout();navigate('/login');}}><LogOut size={16}/></button></div></>;
 return <div className="flex h-dvh overflow-hidden bg-slate-50"><a href="#main-content" className="skip-link">Skip to content</a><aside className="hidden md:flex w-60 shrink-0 flex-col border-r border-slate-200 bg-white">{nav}</aside>{mobile&&<div className="fixed inset-0 z-50 bg-slate-900/40 flex"><aside className="w-72 bg-white flex flex-col h-full">{nav}</aside><button className="m-4 text-white self-start" aria-label="Close navigation" onClick={()=>setMobile(false)}><X/></button></div>}<div className="flex flex-1 min-w-0 flex-col"><header className="h-16 shrink-0 flex items-center gap-4 border-b border-slate-200 bg-white px-5 md:px-8"><button className="md:hidden icon-button" aria-label="Open navigation" onClick={()=>setMobile(true)}><Menu size={19}/></button><span className="text-xs text-slate-400 hidden sm:inline">Workspace</span><span className="text-slate-300 hidden sm:inline">/</span><span className="text-xs font-medium">{title}</span><form className="ml-auto hidden lg:flex items-center gap-2 text-slate-400" onSubmit={e=>{e.preventDefault();navigate(`/quotations?search=${encodeURIComponent(search)}`);}}><Search size={16}/><input aria-label="Search deals" className="!border-0 !bg-transparent !shadow-none !min-h-8 !w-48 !text-xs" placeholder="Find a quotation…" value={search} onChange={e=>setSearch(e.target.value)}/><kbd className="text-[11px] border border-slate-200 rounded px-1.5">↵</kbd></form><button className="icon-button ml-auto lg:ml-0" aria-label="Refresh workspace" onClick={()=>qc.invalidateQueries()}><RefreshCw size={16}/></button><span className="border-l border-slate-200 pl-4 text-[11px] text-slate-500 hidden sm:inline">INR</span></header><main id="main-content" className="flex-1 overflow-y-auto p-5 md:p-8"><div className="mx-auto max-w-[1500px]">{children}</div></main><footer className="border-t border-slate-200 bg-white px-6 py-2 text-[10px] text-slate-500 flex justify-between"><span>DealFlow360</span><span>Connected quotation, inventory and billing</span></footer></div></div>;
}
