# Generated by Django 5.2.17 on 2026-09-05 07:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalChain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('min_overage_threshold', models.DecimalField(decimal_places=2, help_text='Minimum blended overage score for this chain step', max_digits=5)),
                ('max_overage_threshold', models.DecimalField(decimal_places=2, help_text='Maximum blended overage score for this chain step', max_digits=5)),
                ('requires_finance', models.BooleanField(default=False, help_text='If True, needs Finance approval after Manager')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'quotations_approval_chain',
                'ordering': ['min_overage_threshold'],
            },
        ),
        migrations.CreateModel(
            name='DiscountTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier_key', models.CharField(help_text='Must match Customer.Tier choices: bronze, silver, gold', max_length=10, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('max_discount_percent', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'db_table': 'quotations_discount_tier',
                'ordering': ['max_discount_percent'],
            },
        ),
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_approval', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('confirmed', 'Confirmed'), ('under_negotiation', 'Under Negotiation')], default='draft', max_length=20)),
                ('blended_risk_score', models.DecimalField(decimal_places=4, default=0, help_text='Computed by risk_score service on submit', max_digits=8)),
                ('required_approval_level', models.CharField(choices=[('none', 'No Approval Needed'), ('manager', 'Manager Only'), ('manager_finance', 'Manager + Finance')], default='none', max_length=20)),
                ('manager_approved', models.BooleanField(default=False)),
                ('finance_approved', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('payment_terms', models.CharField(default='Net 30 Days', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quotations', to='core.customer')),
                ('sales_rep', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quotations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'quotations_quotation',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('returned', 'Returned for Revision'), ('resubmitted', 'Resubmitted')], max_length=20)),
                ('role_at_action', models.CharField(blank=True, max_length=20)),
                ('reason', models.TextField(blank=True)),
                ('blended_risk_score_at_action', models.DecimalField(decimal_places=4, default=0, max_digits=8)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='approval_actions', to=settings.AUTH_USER_MODEL)),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_logs', to='quotations.quotation')),
            ],
            options={
                'db_table': 'quotations_approval_log',
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='QuotationLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('discount_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quotation_lines', to='core.product')),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='quotations.quotation')),
            ],
            options={
                'db_table': 'quotations_quotation_line',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='CategoryDiscountCeiling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_discount_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discount_ceilings', to='core.productcategory')),
                ('discount_tier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_ceilings', to='quotations.discounttier')),
            ],
            options={
                'db_table': 'quotations_category_discount_ceiling',
                'ordering': ['discount_tier', 'category'],
                'unique_together': {('category', 'discount_tier')},
            },
        ),
    ]
