# Generated by Django 5.2.17 on 2026-09-05 08:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalChainRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('min_over_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('max_over_pct', models.DecimalField(decimal_places=2, default=100, max_digits=5)),
                ('requires_manager', models.BooleanField(default=True)),
                ('requires_finance', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'quotations_approval_chain_rule',
                'ordering': ['min_over_pct'],
            },
        ),
        migrations.CreateModel(
            name='PriceList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('tier', models.CharField(choices=[('bronze', 'Bronze'), ('silver', 'Silver'), ('gold', 'Gold')], max_length=10)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'quotations_price_list',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('sku', models.CharField(blank=True, max_length=50, unique=True)),
                ('category', models.CharField(choices=[('hardware', 'Hardware'), ('services', 'Services'), ('subscriptions', 'Subscriptions'), ('software', 'Software')], db_index=True, max_length=20)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('unit', models.CharField(default='unit', max_length=20)),
                ('tax_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('description', models.TextField(blank=True)),
                ('is_subscription', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'quotations_product',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('company', models.CharField(blank=True, max_length=200)),
                ('address', models.TextField(blank=True)),
                ('tier', models.CharField(choices=[('bronze', 'Bronze'), ('silver', 'Silver'), ('gold', 'Gold')], db_index=True, default='bronze', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'quotations_customer',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DiscountTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.CharField(choices=[('bronze', 'Bronze'), ('silver', 'Silver'), ('gold', 'Gold')], db_index=True, max_length=10)),
                ('category', models.CharField(choices=[('hardware', 'Hardware'), ('services', 'Services'), ('subscriptions', 'Subscriptions'), ('software', 'Software')], db_index=True, max_length=20)),
                ('max_discount_pct', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'db_table': 'quotations_discount_tier',
                'ordering': ['tier', 'category'],
                'unique_together': {('tier', 'category')},
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=100)),
                ('extra_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='quotations.product')),
            ],
            options={
                'db_table': 'quotations_product_variant',
            },
        ),
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote_number', models.CharField(db_index=True, max_length=20, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_approval', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('sent', 'Sent'), ('under_negotiation', 'Under Negotiation'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('fulfillment', 'Fulfillment'), ('invoiced', 'Invoiced'), ('paid', 'Paid')], db_index=True, default='draft', max_length=20)),
                ('blended_risk_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('required_approval_level', models.CharField(choices=[('none', 'No Approval Needed'), ('manager', 'Manager Only'), ('manager_finance', 'Manager + Finance')], default='none', max_length=20)),
                ('manager_approved', models.BooleanField(default=False)),
                ('finance_approved', models.BooleanField(default=False)),
                ('payment_terms', models.CharField(default='Net 30 Days', max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('portal_token', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotations', to='quotations.customer')),
                ('rep', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotations_as_rep', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'quotations_quotation',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_order', models.PositiveIntegerField(default=1)),
                ('role_required', models.CharField(default='sales_manager', max_length=20)),
                ('action', models.CharField(choices=[('submitted', 'Submitted for Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('returned', 'Returned for Revision'), ('re_submitted', 'Re-submitted')], max_length=20)),
                ('note', models.TextField(blank=True)),
                ('blended_risk_score_at_action', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_actions', to=settings.AUTH_USER_MODEL)),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_logs', to='quotations.quotation')),
            ],
            options={
                'db_table': 'quotations_approval_log',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuotationLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=300)),
                ('qty', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('discount_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('line_limit_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('is_subscription', models.BooleanField(default=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotation_lines', to='quotations.product')),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='quotations.quotation')),
            ],
            options={
                'db_table': 'quotations_quotation_line',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PriceListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('price_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='quotations.pricelist')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_list_items', to='quotations.product')),
            ],
            options={
                'db_table': 'quotations_price_list_item',
                'unique_together': {('price_list', 'product')},
            },
        ),
    ]
