# Generated by Django 5.2.17 on 2026-09-05 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='quotationline',
            name='cost_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='quotationline',
            name='tax_pct',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='quotationline',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='quotations.productvariant'),
        ),
        migrations.AlterField(
            model_name='pricelist',
            name='currency',
            field=models.CharField(default='INR', max_length=3),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('base_price__gte', 0), ('cost_price__gte', 0)), name='product_prices_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('tax_pct__gte', 0), ('tax_pct__lte', 100)), name='product_tax_range'),
        ),
        migrations.AddConstraint(
            model_name='quotationline',
            constraint=models.CheckConstraint(condition=models.Q(('qty__gt', 0), ('unit_price__gte', 0)), name='quote_line_positive_quantity_price'),
        ),
        migrations.AddConstraint(
            model_name='quotationline',
            constraint=models.CheckConstraint(condition=models.Q(('discount_pct__gte', 0), ('discount_pct__lte', 100)), name='quote_line_discount_range'),
        ),
    ]
