# Generated by Django 5.2.17 on 2026-09-05 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0003_quotationline_cost_price_quotationline_tax_pct_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('base_price__gte', 0), ('cost_price__gte', 0)), name='product_prices_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('tax_pct__gte', 0), ('tax_pct__lte', 100)), name='product_tax_range'),
        ),
        migrations.AddConstraint(
            model_name='quotationline',
            constraint=models.CheckConstraint(condition=models.Q(('qty__gt', 0), ('unit_price__gte', 0)), name='quote_line_positive_quantity_price'),
        ),
        migrations.AddConstraint(
            model_name='quotationline',
            constraint=models.CheckConstraint(condition=models.Q(('discount_pct__gte', 0), ('discount_pct__lte', 100)), name='quote_line_discount_range'),
        ),
    ]
