# Generated by Django 5.2.17 on 2026-09-05 18:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_backfill_charge_snapshots'),
        ('quotations', '0004_product_product_prices_nonnegative_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotationline',
            name='subscription_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='billing.subscriptionplan'),
        ),
    ]
