import {useState,useEffect} from 'react';
import {useQuery,useMutation,useQueryClient} from '@tanstack/react-query';
import {Truck,Plus,Trash2,Check,RefreshCw,X} from 'lucide-react';
import {quotationsApi} from '../../api/quotations';
import {ApiClient} from '../../api/client';
import {formatCurrency} from '../../lib/utils';
import {PageHead,Notice,Loading,Empty,Stat} from '../workspace/shared';
type Allocation={id?:number;product_id:number;product_name:string;warehouse_id:number;warehouse_name:string;quantity:number;is_backorder:boolean;estimated_cost:number;status?:string;promised_ship_date?:string};
type Split={splits:Allocation[];persisted:boolean;total_shipments:number;total_estimated_cost:number;has_backorders:boolean;backorder_consolidation_available:boolean};
export function FulfillmentPage(){
 const qc=useQueryClient();const [quoteId,setQuoteId]=useState('');const [edit,setEdit]=useState<Allocation[]|null>(null);
 const quotes=useQuery({queryKey:['quotations'],queryFn:()=>quotationsApi.list()});
 const warehouses=useQuery({queryKey:['warehouse-options'],queryFn:()=>ApiClient.get<{id:number;name:string}[]>('/fulfillment/warehouses/')});
 const eligible=(quotes.data||[]).filter(q=>['approved','sent','confirmed','fulfillment','invoiced','paid'].includes(q.status));
 useEffect(()=>{if(!quoteId&&eligible.length)setQuoteId(String(eligible[0].id));},[quotes.data]);
 const query=useQuery({queryKey:['split',quoteId],queryFn:()=>ApiClient.post<Split>(`/fulfillment/${quoteId}/suggest-split/`),enabled:!!quoteId,refetchInterval:15000});
 const action=useMutation({mutationFn:({path,body}:{path:string;body?:unknown})=>ApiClient.post<{message:string}>(`/fulfillment/${quoteId}/${path}/`,body),onSuccess:()=>{setEdit(null);qc.invalidateQueries();}});
 const selected=eligible.find(q=>String(q.id)===quoteId);const canReserve=selected&&['confirmed','fulfillment','invoiced','paid'].includes(selected.status);const d=query.data;
 return <div className="workspace-page"><PageHead eyebrow="FULFILLMENT OPERATIONS" title="Keep every promise moving." description="Allocate physical goods from live stock, handle backorders and track dispatch."/><div className="filter-bar"><label>Quotation<select value={quoteId} onChange={e=>{setQuoteId(e.target.value);setEdit(null);action.reset();}}><option value="">Select a quotation</option>{eligible.map(q=><option key={q.id} value={q.id}>{q.quote_number} · {q.customer_name} · {q.status}</option>)}</select></label></div><Notice error={quotes.error||query.error||action.error}/><Notice message={action.isSuccess?action.data.message:undefined}/>{!canReserve&&selected&&<Notice message="This is an allocation preview. Customer confirmation is required before inventory can be reserved."/>}{d&&<><div className="metrics-grid three"><Stat label="Shipment locations" value={d.total_shipments} note="Distinct warehouses with allocated stock"/><Stat label="Estimated freight" value={formatCurrency(d.total_estimated_cost)} note="Configured per-unit warehouse cost weight"/><Stat label="Backordered units" value={d.splits.filter(s=>s.is_backorder).reduce((n,s)=>n+s.quantity,0)} note="Units waiting for inventory" accent/></div>{d.backorder_consolidation_available&&<div className="notice"><Truck size={18}/><span>Fresh stock can cover remaining backorders.</span><button className="btn btn-primary btn-sm" disabled={action.isPending} onClick={()=>action.mutate({path:'consolidate'})}>Consolidate remaining backorder</button></div>}</>}
 <section className="panel"><div className="panel-head"><div><div className="eyebrow">{d?.persisted?'SAVED ALLOCATIONS':'LIVE STOCK PREVIEW'}</div><h2>Warehouse allocations</h2></div><div className="page-actions">{canReserve&&d?.splits.length&&!d.splits.some(s=>['shipped','delivered'].includes(s.status||''))?<><button className="btn btn-secondary btn-sm" onClick={()=>{setEdit(d.splits.map(s=>({...s})));action.reset();}}>Manual override</button>{!d.persisted&&<button className="btn btn-primary btn-sm" disabled={action.isPending} onClick={()=>action.mutate({path:'accept-split'})}><Check size={14}/>Accept suggested split</button>}</>:null}</div></div>{query.isLoading?<Loading/>:!d?.splits.length?<Empty title="No physical shipments" text="Select a quotation with hardware. Services and subscriptions never reserve warehouse stock."/>:<div className="table-scroll"><table className="data-table"><thead><tr><th>Product</th><th>Warehouse</th><th>Units</th><th>Estimated freight</th><th>Status</th><th>Promised ship date</th><th>Action</th></tr></thead><tbody>{d.splits.map((s,i)=><tr key={s.id||i}><td><strong>{s.product_name}</strong></td><td>{s.warehouse_name}</td><td>{s.quantity}</td><td>{formatCurrency(s.estimated_cost)}</td><td><span className={`pill ${s.is_backorder?'pill-amber':'pill-green'}`}>{s.is_backorder?'Backorder':s.status||'Suggested'}</span></td><td>{s.id&&!['shipped','delivered'].includes(s.status||'')?<input aria-label={`Promised ship date for ${s.product_name} at ${s.warehouse_name}`} type="date" defaultValue={s.promised_ship_date||''} onBlur={e=>{if(e.target.value&&e.target.value!==s.promised_ship_date)action.mutate({path:`shipments/${s.id}`,body:{action:'promise',date:e.target.value}});}}/>:s.promised_ship_date||'—'}</td><td>{s.id&&!s.is_backorder&&['accepted','overridden','shipped'].includes(s.status||'')&&<button className="btn btn-secondary btn-sm" disabled={action.isPending} onClick={()=>action.mutate({path:`shipments/${s.id}`,body:{action:s.status==='shipped'?'deliver':'ship'}})}>{s.status==='shipped'?'Mark delivered':'Mark dispatched'}</button>}</td></tr>)}</tbody></table></div>}</section>
 {edit&&<div className="modal-backdrop"><section className="editor-modal" role="dialog" aria-modal="true" aria-labelledby="allocation-title"><div className="panel-head"><h2 id="allocation-title">Adjust warehouse allocations</h2><button className="icon-button" aria-label="Close allocations" onClick={()=>setEdit(null)}><X/></button></div><form onSubmit={e=>{e.preventDefault();action.mutate({path:'override-split',body:{allocations:edit.map(s=>({product_id:s.product_id,warehouse_id:Number(s.warehouse_id),quantity:Number(s.quantity),is_backorder:s.is_backorder}))}});}}><p className="muted mb-4">Each product’s total must match the confirmed order. Existing reservations are released and replaced in one transaction.</p>{edit.map((s,i)=><div className="allocation-editor" key={i}><strong>{s.product_name}</strong><label>Warehouse<select value={s.warehouse_id} onChange={e=>setEdit(edit.map((a,j)=>j===i?{...a,warehouse_id:Number(e.target.value)}:a))}>{warehouses.data?.map(w=><option key={w.id} value={w.id}>{w.name}</option>)}</select></label><label>Units<input type="number" min="1" required value={s.quantity} onChange={e=>setEdit(edit.map((a,j)=>j===i?{...a,quantity:Number(e.target.value)}:a))}/></label><label className="check-label">Backorder<input type="checkbox" checked={s.is_backorder} onChange={e=>setEdit(edit.map((a,j)=>j===i?{...a,is_backorder:e.target.checked}:a))}/></label><div className="page-actions"><button className="btn btn-secondary btn-sm" type="button" onClick={()=>setEdit([...edit,{...s,id:undefined,quantity:1}])}><Plus size={13}/>Split row</button><button className="icon-button" type="button" aria-label={`Remove allocation ${i+1}`} onClick={()=>setEdit(edit.filter((_,j)=>i!==j))}><Trash2 size={14}/></button></div></div>)}<Notice error={action.error}/><div className="modal-actions"><button disabled={action.isPending} className="btn btn-primary">Save allocations</button></div></form></section></div>}
 </div>;
}
