import {useState} from 'react';
import {useNavigate} from 'react-router-dom';
import {Layers,ArrowRight,ShieldCheck,Eye,EyeOff} from 'lucide-react';
import {useAuth} from '../../context/AuthContext';
import {ApiClient} from '../../api/client';
import {Notice} from '../workspace/shared';
export function LoginPage(){
 const {login}=useAuth();const navigate=useNavigate();const [signup,setSignup]=useState(false);const [username,setUsername]=useState('');const [password,setPassword]=useState('');const [email,setEmail]=useState('');const [name,setName]=useState('');const [show,setShow]=useState(false);const [busy,setBusy]=useState(false);const [error,setError]=useState<unknown>();const [success,setSuccess]=useState('');
 const submit=async(e:React.FormEvent)=>{e.preventDefault();setBusy(true);setError(null);try{if(signup){const result=await ApiClient.post<{message:string}>('/auth/register/',{username,password,email,first_name:name});setSuccess(result.message);setSignup(false);setPassword('');return;}await login(username,password);navigate('/dashboard');}catch(err){setError(err);}finally{setBusy(false);}};
 return <div className="login-layout"><section className="login-story"><div className="brand"><span className="brand-mark"><Layers size={25}/></span><span>DealFlow<span className="brand-360">360</span></span></div><div className="login-story-copy"><span className="hero-kicker">A BETTER WAY TO CLOSE</span><h1>Less friction.<br/>More <em>forward.</em></h1><p>Bring every conversation, approval and commitment into one connected sales workspace.</p><div className="login-flow"><span>Quote</span><ArrowRight/><span>Approve</span><ArrowRight/><span>Fulfil</span><ArrowRight/><span>Get paid</span></div></div><div className="login-story-footer"><ShieldCheck size={18}/>Built for thoughtful sales teams.</div></section><section className="login-form-area"><div className="login-form-wrap"><span className="eyebrow">YOUR NEXT CHAPTER STARTS HERE</span><h2>{signup?'Make yourself at home.':'Welcome back.'}</h2><p>{signup?'Create a sales representative account.':'Sign in to keep good business moving.'}</p><form onSubmit={submit}>{signup&&<><label>Your name<input required autoComplete="given-name" value={name} onChange={e=>setName(e.target.value)}/></label><label>Work email<input required type="email" autoComplete="email" value={email} onChange={e=>setEmail(e.target.value)}/></label></>}<label>Username<input required autoComplete="username" placeholder="Enter your username" value={username} onChange={e=>setUsername(e.target.value)}/></label><label>Password<div className="password-field"><input required minLength={signup?10:undefined} type={show?'text':'password'} autoComplete={signup?'new-password':'current-password'} placeholder={signup?'At least 10 characters':'Enter your password'} value={password} onChange={e=>setPassword(e.target.value)}/><button type="button" aria-label={show?'Hide password':'Show password'} onClick={()=>setShow(!show)}>{show?<EyeOff size={18}/>:<Eye size={18}/>}</button></div></label><Notice error={error} message={success}/><button disabled={busy} className="btn btn-primary full-width">{busy?'Please wait…':signup?'Create account':'Sign in to workspace'}<ArrowRight size={17}/></button></form><p className="login-switch">{signup?'Already have an account?':'New to the workspace?'} <button onClick={()=>{setSignup(!signup);setError(null);}}>{signup?'Sign in':'Create an account'}</button></p><div className="login-security"><ShieldCheck size={17}/><span>Your access follows your assigned role.<br/>Customer? Open your private quotation link.</span></div></div><span className="login-copyright">© {new Date().getFullYear()} DealFlow360</span></section></div>;
}
