import { useQuery } from '@tanstack/react-query';
import { Link } from 'react-router-dom';
import { ArrowUpRight, ArrowRight, ShieldCheck, Clock, Layers, CircleCheck } from 'lucide-react';
import { useAuth } from '../../context/AuthContext';
import { quotationsApi } from '../../api/quotations';
import { ApiClient } from '../../api/client';
import { formatCurrency, getStatusLabel, timeAgo } from '../../lib/utils';
import { PageHead, Stat, Notice, Loading, Empty, NewQuote } from './shared';
import { Report } from './ReportsPage';

export function Dashboard() {
  const {user}=useAuth();
  const query=useQuery({queryKey:['reports','dashboard'],queryFn:()=>ApiClient.get<Report>('/reports/'),refetchInterval:30000});
  const deals=useQuery({queryKey:['quotations'],queryFn:()=>quotationsApi.list(),refetchInterval:30000});
  const s=query.data?.summary;
  const stages=query.data?.stages || {};
  const total=query.data?.summary.count || 0;
  const pending=(deals.data || []).filter(q=>q.status==='pending_approval');
  const stageList=[['draft','Draft','#83988b'],['pending_approval','In review','#d5ab54'],['approved','Approved','#7dada0'],['sent','With customer','#385a51'],['confirmed','Confirmed','#163f35']];
  return <div className="workspace-page"><PageHead eyebrow="YOUR REVENUE WORKSPACE" title={`Good to see you, ${user?.first_name || user?.username}.`} description="A clear view of every deal. A confident next step."><span className="date-chip">{new Date().toLocaleDateString('en-IN',{day:'numeric',month:'long',year:'numeric'})}</span><NewQuote/></PageHead>
  <Notice error={query.error||deals.error}/>{query.isLoading?<Loading/>:s&&<>
  <section className="overview-hero"><div className="hero-copy"><span className="hero-kicker"><span className="live-dot"/>YOUR PIPELINE, IN MOTION</span><h2>Good deals deserve<br/><em>a better flow.</em></h2><p>From the first quote to the final payment.<br/>Keep pricing, people and promises in sync.</p><Link to="/quotations" className="hero-link">Explore your pipeline <ArrowUpRight size={18}/></Link></div><div className="flow-art" aria-label="Quote to cash workflow"><div className="orbit orbit-one"/><div className="orbit orbit-two"/><div className="flow-center"><Layers size={32}/><span>DealFlow<span>360</span></span></div><div className="flow-node node-one"><span>01</span>Quote<CircleCheck size={14}/></div><div className="flow-node node-two"><span>02</span>Approve<ShieldCheck size={14}/></div><div className="flow-node node-three"><span>03</span>Fulfil<Layers size={14}/></div><div className="flow-node node-four"><span>04</span>Get paid<ArrowUpRight size={14}/></div></div><div className="hero-bottom"><span>PRICING DISCIPLINE</span><span>CONNECTED OPERATIONS</span><span>CUSTOMER COLLABORATION</span></div></section>
  <div className="metrics-grid"><Stat label="Active pipeline" value={formatCurrency(s.pipeline)} note={`${total} quotations in your workspace`} accent/><Stat label="Confirmed bookings" value={formatCurrency(s.bookings)} note="Accepted order value, excluding tax"/><Stat label="Awaiting approval" value={stages.pending_approval || 0} note="Deals needing a pricing decision"/><Stat label="Average margin" value={`${s.margin}%`} note="Calculated from configured costs"/></div>
  <div className="dashboard-grid"><section className="panel"><div className="panel-head"><div><div className="eyebrow">DEAL MOMENTUM</div><h2>Your pipeline at a glance</h2></div><Link className="text-link" to="/reports">View report <ArrowUpRight size={15}/></Link></div><div className="stage-chart">{stageList.map(([key,label,color])=><Link to={`/quotations?status=${key}`} className="stage-row" key={key}><span>{label}</span><div className="stage-track"><div style={{width:`${total?Math.max(3,(stages[key]||0)/total*100):0}%`,background:color}}/></div><strong>{stages[key]||0}</strong></Link>)}</div><div className="panel-foot">Every stage reflects saved quotations. Updated every 30 seconds.</div></section>
  <section className="panel attention-panel"><div className="panel-head"><div><div className="eyebrow">NEXT BEST ACTION</div><h2>Needs a decision</h2></div><span className="count-dot">{pending.length}</span></div>{pending.length?pending.slice(0,3).map(q=><Link key={q.id} to={user?.role==='sales_rep'?`/quotations/${q.id}`:`/approvals/${q.id}`} className="attention-row"><div className="attention-icon"><ShieldCheck size={18}/></div><div><strong>{q.customer_name}</strong><small>{q.quote_number} · {formatCurrency(q.total_amount)}</small></div><ArrowUpRight size={16}/></Link>):<Empty title="You're all caught up" text="New pricing exceptions will appear here."/>}<Link className="panel-foot text-link" to="/deal-health">Check deal health <ArrowRight size={15}/></Link></section></div>
  <section className="panel"><div className="panel-head"><div><div className="eyebrow">THE LATEST IN YOUR WORKSPACE</div><h2>Recent quotations</h2></div><Link to="/quotations" className="text-link">View all <ArrowUpRight size={15}/></Link></div>{deals.data?.length?<div className="table-scroll"><table className="data-table"><thead><tr><th>Customer / Quotation</th><th>Stage</th><th>Net value</th><th>Representative</th><th>Last activity</th><th/></tr></thead><tbody>{deals.data.slice(0,5).map(q=><tr key={q.id}><td><Link to={`/quotations/${q.id}`}><strong>{q.customer_name}</strong><small>{q.quote_number}</small></Link></td><td><span className={`pill ${['approved','confirmed','paid'].includes(q.status)?'pill-green':q.status==='pending_approval'?'pill-amber':''}`}>{getStatusLabel(q.status)}</span></td><td className="numeric">{formatCurrency(q.total_amount)}</td><td>{q.rep_name}</td><td className="muted">{timeAgo(q.updated_at)}</td><td><Link aria-label={`Open ${q.quote_number}`} to={`/quotations/${q.id}`}><ArrowUpRight size={17}/></Link></td></tr>)}</tbody></table></div>:<Empty title="Your first deal starts here" text="Create a quotation to bring your pipeline to life."/>}</section></>}
  </div>;
}
