import {useState} from 'react';
import {useQuery,useMutation} from '@tanstack/react-query';
import {Link} from 'react-router-dom';
import {CheckCircle2,AlertCircle,SlidersHorizontal} from 'lucide-react';
import {ApiClient} from '../../api/client';
import {formatCurrency} from '../../lib/utils';
import {Notice} from './shared';
type Scenario={name:string;net:string;tax:string;total:string;gross_profit:string;margin:string;risk:string;approval:string};
export function DealIntelligence({id,revision}:{id:number;revision?:string}){
 const [discount,setDiscount]=useState('10');
 const ready=useQuery({queryKey:['readiness',id,revision],queryFn:()=>ApiClient.get<{passed:number;total:number;checks:{key:string;title:string;passed:boolean;detail:string;path:string}[]}>(`/quotations/${id}/readiness/`)});
 const simulation=useMutation({mutationFn:()=>ApiClient.post<{scenarios:Scenario[]}>(`/quotations/${id}/scenarios/`,{discount})});
 return <div className="grid grid-cols-1 xl:grid-cols-[1fr_1.4fr] gap-6 mt-6"><section className="panel"><div className="panel-head"><h2>Deal readiness</h2><span className="pill">{ready.data?.passed||0} / {ready.data?.total||5} checks</span></div><Notice error={ready.error}/><div className="divide-y divide-slate-100">{ready.data?.checks.map(c=><div key={c.key} className="flex gap-3 px-5 py-4">{c.passed?<CheckCircle2 size={17} className="text-emerald-600 shrink-0 mt-0.5"/>:<AlertCircle size={17} className="text-amber-600 shrink-0 mt-0.5"/>}<div><strong className="block text-xs font-semibold">{c.title}</strong><p className="text-xs text-slate-500 mt-1 leading-relaxed">{c.detail}</p>{!c.passed&&<Link className="text-xs text-blue-600 inline-block mt-2" to={c.path}>Review →</Link>}</div></div>)}</div></section><section className="panel"><div className="panel-head"><div><h2>Pricing scenario lab</h2><p className="muted mt-1">Compare economics before changing the quotation.</p></div><SlidersHorizontal size={18} className="text-slate-400"/></div><form className="flex gap-3 items-end px-5 py-5" onSubmit={e=>{e.preventDefault();simulation.mutate();}}><label className="flex-1">Proposed discount across all lines (%)<input required type="number" min="0" max="100" step="0.01" value={discount} onChange={e=>setDiscount(e.target.value)}/></label><button className="btn btn-primary" disabled={simulation.isPending}>Compare terms</button></form><Notice error={simulation.error}/>{simulation.data?<div className="table-scroll"><table className="data-table"><thead><tr><th>Scenario</th><th>Net amount</th><th>Gross profit</th><th>Margin</th><th>Approval</th></tr></thead><tbody>{simulation.data.scenarios.map(s=><tr key={s.name}><td><strong>{s.name}</strong></td><td>{formatCurrency(s.net)}</td><td>{formatCurrency(s.gross_profit)}</td><td>{s.margin}%</td><td><span className={`pill ${s.approval==='none'?'pill-green':'pill-amber'}`}>{s.approval==='none'?'Within policy':s.approval.replaceAll('_',' + ')}</span></td></tr>)}</tbody></table></div>:<div className="px-5 pb-6 text-xs text-slate-500 leading-relaxed">Compare the current quote with a proposed order-wide discount and a version capped at your configured discount ceilings. Costs, tax snapshots and approval rules come from the live deal engine.</div>}<div className="panel-foot">Scenarios are previews. Apply your chosen terms in the quotation editor and submit for approval.</div></section></div>;
}
