import { useState } from 'react';
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { Link } from 'react-router-dom';
import { Receipt, X, Check } from 'lucide-react';
import { ApiClient } from '../../api/client';
import { useAuth } from '../../context/AuthContext';
import { formatCurrency } from '../../lib/utils';
import { PageHead, Stat, Notice, Loading, Empty } from './shared';
type Invoice={id:number;invoice_number:string;quotation:number;quote_number:string;customer:string;type:string;amount:string;paid_amount:string;balance:string;credit_amount:string;refund_due:string;status:string;due_date:string};
export function InvoicesPage() {
 const {user}=useAuth();const qc=useQueryClient();
 const query=useQuery({queryKey:['invoices'],queryFn:()=>ApiClient.get<Invoice[]>('/invoices/')});
 const [selected,setSelected]=useState<Invoice|null>(null);const [amount,setAmount]=useState('');const [reference,setReference]=useState('');const [method,setMethod]=useState('bank_transfer');
 const pay=useMutation({mutationFn:()=>ApiClient.post(`/invoices/${selected!.id}/payments/`,{amount,reference,method}),onSuccess:()=>{setSelected(null);qc.invalidateQueries();}});
 const rows=query.data||[];const canPay=['admin','finance'].includes(user?.role||'');
 return <div className="workspace-page"><PageHead eyebrow="CASH & COLLECTIONS" title="Close the loop." description="Track invoices, reconcile receipts and see exactly what is outstanding."/><div className="metrics-grid three"><Stat label="Total invoiced" value={formatCurrency(rows.reduce((s,r)=>s+Number(r.amount),0))} note="One-time, recurring and adjustment invoices"/><Stat label="Payments recorded" value={formatCurrency(rows.reduce((s,r)=>s+Number(r.paid_amount),0))} note="Receipts entered by your finance team" accent/><Stat label="Outstanding" value={formatCurrency(rows.reduce((s,r)=>s+Number(r.balance),0))} note="Remaining balance across all invoices"/></div><Notice error={query.error}/><Notice message={pay.isSuccess?'Payment recorded and invoice balance updated.':undefined}/><section className="panel"><div className="panel-head"><h2>Invoice ledger</h2><span className="muted">{rows.length} invoices</span></div>{query.isLoading?<Loading/>:rows.length?<div className="table-scroll"><table className="data-table"><thead><tr><th>Invoice / Customer</th><th>Type</th><th>Amount</th><th>Credits / Refund due</th><th>Outstanding</th><th>Due date</th><th>Status</th><th/></tr></thead><tbody>{rows.map(i=><tr key={i.id}><td><Link to={`/quotations/${i.quotation}`}><strong>{i.customer}</strong><small>{i.invoice_number}</small></Link></td><td>{i.type.replace('_',' ')}</td><td>{formatCurrency(i.amount)}</td><td>{formatCurrency(i.credit_amount)}{Number(i.refund_due)>0&&<small>Refund due: {formatCurrency(i.refund_due)}</small>}</td><td>{formatCurrency(i.balance)}</td><td>{i.due_date}</td><td><span className={`pill ${i.status==='paid'?'pill-green':'pill-amber'}`}>{i.status}</span></td><td>{canPay&&Number(i.balance)>0&&<button className="btn btn-secondary btn-sm" onClick={()=>{setSelected(i);setAmount(i.balance);setReference('');pay.reset();}}>Record payment</button>}</td></tr>)}</tbody></table></div>:<Empty title="No invoices yet" text="Invoices are created when a customer confirms an approved quotation."/>}</section>
 {selected&&<div className="modal-backdrop"><section className="editor-modal compact" role="dialog" aria-modal="true" aria-labelledby="payment-title"><div className="panel-head"><h2 id="payment-title">Record a payment</h2><button className="icon-button" aria-label="Close payment" onClick={()=>setSelected(null)}><X/></button></div><p>{selected.invoice_number} · {selected.customer}</p><form onSubmit={e=>{e.preventDefault();pay.mutate();}}><label>Amount received (INR)<input required type="number" min="0.01" step="0.01" max={selected.balance} value={amount} onChange={e=>setAmount(e.target.value)}/></label><label>Payment method<select value={method} onChange={e=>setMethod(e.target.value)}><option value="bank_transfer">NEFT / RTGS / IMPS</option><option value="upi">UPI</option><option value="card">Card</option><option value="cash">Cash</option></select></label><label>UTR / receipt reference<input required minLength={3} maxLength={100} placeholder="Enter the actual transaction reference" value={reference} onChange={e=>setReference(e.target.value)}/></label><p className="muted">Record a payment already received. This action does not initiate a bank transfer.</p><Notice error={pay.error}/><div className="modal-actions"><button className="btn btn-primary" disabled={pay.isPending}><Check size={16}/>{pay.isPending?'Recording…':'Record receipt'}</button></div></form></section></div>}
 </div>;
}
