import {useState,useEffect} from 'react';
import {useQuery,useMutation,useQueryClient} from '@tanstack/react-query';
import {Link} from 'react-router-dom';
import {X,ArrowUpRight} from 'lucide-react';
import {quotationsApi} from '../../api/quotations';
import {getBillingSchedule,prorateSubscription,cancelSubscription,RecurringLine} from '../../api/billing';
import {useAuth} from '../../context/AuthContext';
import {formatCurrency} from '../../lib/utils';
import {PageHead,Notice,Loading,Empty,Stat} from '../workspace/shared';
export function BillingPage(){
 const {user}=useAuth();const qc=useQueryClient();const [quoteId,setQuoteId]=useState('');const [edit,setEdit]=useState<RecurringLine|null>(null);const [cancel,setCancel]=useState<RecurringLine|null>(null);const [planId,setPlanId]=useState('');const [quantity,setQuantity]=useState('1');const [date,setDate]=useState(new Date().toLocaleDateString('en-CA'));
 const quotes=useQuery({queryKey:['quotations'],queryFn:()=>quotationsApi.list()});
 const eligible=(quotes.data||[]).filter(q=>['confirmed','fulfillment','invoiced','paid'].includes(q.status));
 useEffect(()=>{if(!quoteId&&eligible.length)setQuoteId(String(eligible[0].id));},[quotes.data]);
 const query=useQuery({queryKey:['billing',quoteId],queryFn:()=>getBillingSchedule(Number(quoteId)),enabled:!!quoteId});
 const modify=useMutation({mutationFn:()=>prorateSubscription(edit!.line_id,{new_quantity:Number(quantity),change_date:date,...(planId?{new_plan_id:Number(planId)}:{})}),onSuccess:()=>{setEdit(null);qc.invalidateQueries();}});
 const cancellation=useMutation({mutationFn:()=>cancelSubscription(cancel!.line_id),onSuccess:()=>{setCancel(null);qc.invalidateQueries();}});
 const canManage=['finance','admin'].includes(user?.role||'');const d=query.data;
 return <div className="workspace-page"><PageHead eyebrow="RECURRING REVENUE" title="Subscription agreements" description="Manage real subscription agreements alongside one-time purchases."><Link className="btn btn-secondary" to="/invoices">Invoice ledger <ArrowUpRight size={15}/></Link></PageHead><div className="filter-bar"><label>Confirmed order<select value={quoteId} onChange={e=>{setQuoteId(e.target.value);modify.reset();cancellation.reset();}}><option value="">Choose an order</option>{eligible.map(q=><option value={q.id} key={q.id}>{q.quote_number} · {q.customer_name}</option>)}</select></label></div><Notice error={query.error||quotes.error}/><Notice message={modify.isSuccess?'Subscription updated. The proration adjustment is saved in billing.':cancellation.isSuccess?`Subscription cancelled. Credit recorded: ${formatCurrency(cancellation.data.credit_note_amount)}`:undefined}/>{d&&<div className="metrics-grid three"><Stat label="One-time net amount" value={formatCurrency(d.total_one_time)} note="Hardware and services, excluding tax"/><Stat label="Recurring agreement value" value={formatCurrency(d.total_recurring)} note="Per configured cycle; see each plan below" accent/><Stat label="Subscription lines" value={d.recurring_lines.length} note="Created when the customer accepted the order"/></div>}
 <section className="panel"><div className="panel-head"><h2>Subscription agreements</h2><span className="muted">Proration uses actual calendar days</span></div>{query.isLoading?<Loading/>:!d?.recurring_lines.length?<Empty title="No active agreements to display" text="Confirm a quotation with a recurring product to create a subscription."/>:<div className="table-scroll"><table className="data-table"><thead><tr><th>Product / Plan</th><th>Quantity</th><th>Cycle amount</th><th>Next invoice</th><th>Status</th><th>Credits</th><th>Manage</th></tr></thead><tbody>{d.recurring_lines.map(l=><tr key={l.line_id}><td><strong>{l.product_name}</strong><small>{l.subscription?.plan_name||'Not activated'}</small></td><td>{l.quantity}</td><td>{formatCurrency(l.subscription?.plan_price||0)}<small>{l.subscription?.billing_cycle}</small></td><td>{l.subscription?.status==='cancelled'?'—':l.subscription?.next_billing_date||'—'}</td><td><span className={`pill ${l.subscription?.status==='cancelled'?'':'pill-green'}`}>{l.subscription?.status||'Not activated'}</span></td><td>{formatCurrency(l.subscription?.credit_note_amount||0)}</td><td>{canManage&&l.subscription&&l.subscription.status!=='cancelled'&&<div className="page-actions"><button className="btn btn-secondary btn-sm" onClick={()=>{setEdit(l);setPlanId('');setDate(new Date().toLocaleDateString('en-CA'));setQuantity(l.quantity);modify.reset();}}>Modify</button><button className="btn btn-secondary btn-sm" onClick={()=>{setCancel(l);cancellation.reset();}}>Cancel</button></div>}</td></tr>)}</tbody></table></div>}</section>
 {d?.one_time_lines.length?<section className="panel"><div className="panel-head"><h2>One-time purchases</h2></div><div className="table-scroll"><table className="data-table"><thead><tr><th>Product</th><th>Quantity</th><th>Net amount</th></tr></thead><tbody>{d.one_time_lines.map(l=><tr key={l.line_id}><td>{l.product_name}</td><td>{l.quantity}</td><td>{formatCurrency(l.line_total)}</td></tr>)}</tbody></table></div></section>:null}
 {(edit||cancel)&&<div className="modal-backdrop"><section className="editor-modal compact" role="dialog" aria-modal="true" aria-labelledby="subscription-title"><div className="panel-head"><h2 id="subscription-title">{edit?'Modify subscription':'Cancel subscription'}</h2><button className="icon-button" aria-label="Close subscription dialog" onClick={()=>{setEdit(null);setCancel(null);}}><X/></button></div><form onSubmit={e=>{e.preventDefault();edit?modify.mutate():cancellation.mutate();}}><p className="muted mb-5">{edit?'Change quantity or choose another plan for the same billing cycle. The remaining portion of this billed period is charged or credited immediately.':'Cancellation takes effect today. The configured unused-period refund becomes a credit note; no bank refund is sent automatically.'}</p>{edit&&<><label>Plan<select value={planId} onChange={e=>setPlanId(e.target.value)}><option value="">Keep current plan and negotiated rate</option>{edit.subscription.available_plans.map(p=><option key={p.id} value={p.id}>{p.name} · {formatCurrency(p.price)} / unit</option>)}</select></label><label>New quantity<input required type="number" min="1" step="1" value={quantity} onChange={e=>setQuantity(e.target.value)}/></label><label>Effective date<input required type="date" readOnly value={date} onChange={e=>setDate(e.target.value)}/></label></>}<Notice error={modify.error||cancellation.error}/><div className="modal-actions"><button className="btn btn-primary" disabled={modify.isPending||cancellation.isPending}>{edit?'Save change & prorate':'Confirm cancellation'}</button></div></form></section></div>}
 </div>;
}
